name: Deploy via ftp
on: push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@master
      - name: Upload ftp
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 159.89.27.225
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          sftp_only: false
          local_path: './*'
          remote_path: 'public_html/wp-content/themes/acerbo/'
